services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - env/.env
    environment:
      POSTGRES_DB: led_controller_db
      POSTGRES_USER: gmx
      POSTGRES_PASSWORD: 1234

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./srcs:/srcs
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - env/.env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379

  celery:
    build: .
    command: celery -A base_app worker --loglevel=info -E
    volumes:
      - ./srcs:/srcs
    depends_on:
      - db
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  grpc_server:
    build: .
    command: python manage.py grpcrunaioserver 0.0.0.0:50052
    volumes:
      - ./srcs:/srcs
    ports:
      - "50052:50052"
    depends_on:
      - db
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379


volumes:
  postgres_data:
 
