global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["web:8001"]

  # - job_name: "web"
  #   static_configs:
  #     - targets: ["web:8001"]  # Update the target to match your web service
