# Generated by Django 4.2.11 on 2024-04-26 14:25

import colorfield.fields
import django.contrib.postgres.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products_controller", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patternmode",
            name="palette",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=colorfield.fields.ColorField(
                    default="#FFFFFF", image_field=None, max_length=25, samples=None
                ),
                size=None,
            ),
        ),
    ]
