# Generated by Django 4.2.6 on 2023-10-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products_controller", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="videomode",
            name="encoding",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
    ]
