# Generated by Django 4.2.6 on 2023-10-24 11:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products_controller", "0002_videomode_encoding"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videomode",
            name="encoding",
        ),
    ]
