# Generated by Django 4.2.6 on 2023-10-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products_controller", "0003_remove_videomode_encoding"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagemode",
            name="image_low_pixel",
            field=models.ImageField(blank=True, null=True, upload_to="images/low_pixel/"),
        ),
    ]
