# Generated by Django 4.2.6 on 2023-10-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products_controller", "0004_imagemode_image_low_pixel"),
    ]

    operations = [
        migrations.AddField(
            model_name="videomode",
            name="video_low_pixel",
            field=models.ImageField(blank=True, null=True, upload_to="low_pixel_videos/"),
        ),
        migrations.AlterField(
            model_name="imagemode",
            name="image_low_pixel",
            field=models.ImageField(blank=True, null=True, upload_to="low_pixel_images/"),
        ),
    ]
