# Generated by Django 4.2.7 on 2023-11-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products_controller", "0005_videomode_video_low_pixel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videomode",
            name="video_low_pixel",
            field=models.ImageField(blank=True, null=True, upload_to="video_low_pixels/"),
        ),
    ]
