# Generated by Django 4.2.7 on 2023-11-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products_controller", "0006_alter_videomode_video_low_pixel"),
    ]

    operations = [
        migrations.AddField(
            model_name="coffeemachine",
            name="coffee_level",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="coffeemachine",
            name="filter_position",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="coffeemachine",
            name="heat",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="coffeemachine",
            name="mode_value",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="coffeemachine",
            name="used_water_level",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="coffeemachine",
            name="water_level",
            field=models.IntegerField(default=0),
        ),
    ]
