# Generated by Django 4.2.7 on 2023-11-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products_controller", "0007_coffeemachine_coffee_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coffeemachine",
            name="coffee_level",
            field=models.IntegerField(choices=[(1, "ON"), (2, "OFF"), (3, "ERROR")], default=0),
        ),
        migrations.AlterField(
            model_name="coffeemachine",
            name="used_water_level",
            field=models.IntegerField(choices=[(1, "ON"), (2, "OFF"), (3, "ERROR")], default=0),
        ),
        migrations.AlterField(
            model_name="coffeemachine",
            name="water_level",
            field=models.IntegerField(choices=[(1, "ON"), (2, "OFF"), (3, "ERROR")], default=0),
        ),
    ]
