# Generated by Django 4.2.7 on 2023-11-24 15:05

import features.products_controller.models.products.coffee_machine
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products_controller", "0008_alter_coffeemachine_coffee_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coffeemachine",
            name="coffee_level",
            field=models.IntegerField(
                choices=[(0, "EMPTY"), (1, "WARNING"), (2, "FULL")],
                default=features.products_controller.models.products.coffee_machine.ContainerStatus["EMPTY"],
            ),
        ),
        migrations.AlterField(
            model_name="coffeemachine",
            name="used_water_level",
            field=models.IntegerField(
                choices=[(0, "EMPTY"), (1, "WARNING"), (2, "FULL")],
                default=features.products_controller.models.products.coffee_machine.ContainerStatus["EMPTY"],
            ),
        ),
        migrations.AlterField(
            model_name="coffeemachine",
            name="water_level",
            field=models.IntegerField(
                choices=[(0, "EMPTY"), (1, "WARNING"), (2, "FULL")],
                default=features.products_controller.models.products.coffee_machine.ContainerStatus["EMPTY"],
            ),
        ),
    ]
