# Generated by Django 4.2.9 on 2024-01-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products_controller", "0010_remove_patternmode_status_patternmode_blink_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledpanel",
            name="brightness",
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=3),
        ),
    ]
