# Generated by Django 4.2.9 on 2024-02-15 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products_controller", "0011_ledpanel_brightness"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledpanel",
            name="mode",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="products_controller.ledmode"
            ),
        ),
    ]
