# Generated by Django 4.2.10 on 2024-03-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products_controller", "0012_alter_ledpanel_mode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ledpanel",
            name="mode",
        ),
        migrations.AddField(
            model_name="ledpanel",
            name="mode",
            field=models.ManyToManyField(to="products_controller.ledmode"),
        ),
    ]
