# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
from features.products_controller.grpc import (
    products_controller_pb2 as features_dot_products__controller_dot_grpc_dot_products__controller__pb2,
)
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class BaseProductControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
            "/base_app.products_controller.BaseProductController/Create",
            request_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.BaseProductRequest.SerializeToString,
            response_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.BaseProductResponse.FromString,
        )
        self.Destroy = channel.unary_unary(
            "/base_app.products_controller.BaseProductController/Destroy",
            request_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.BaseProductDestroyRequest.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
        self.List = channel.unary_unary(
            "/base_app.products_controller.BaseProductController/List",
            request_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.BaseProductListRequest.SerializeToString,
            response_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.BaseProductListResponse.FromString,
        )
        self.PartialUpdate = channel.unary_unary(
            "/base_app.products_controller.BaseProductController/PartialUpdate",
            request_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.BaseProductPartialUpdateRequest.SerializeToString,
            response_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.BaseProductResponse.FromString,
        )
        self.Retrieve = channel.unary_unary(
            "/base_app.products_controller.BaseProductController/Retrieve",
            request_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.BaseProductRetrieveRequest.SerializeToString,
            response_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.BaseProductResponse.FromString,
        )
        self.Update = channel.unary_unary(
            "/base_app.products_controller.BaseProductController/Update",
            request_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.BaseProductRequest.SerializeToString,
            response_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.BaseProductResponse.FromString,
        )


class BaseProductControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def PartialUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_BaseProductControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Create": grpc.unary_unary_rpc_method_handler(
            servicer.Create,
            request_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.BaseProductRequest.FromString,
            response_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.BaseProductResponse.SerializeToString,
        ),
        "Destroy": grpc.unary_unary_rpc_method_handler(
            servicer.Destroy,
            request_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.BaseProductDestroyRequest.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        "List": grpc.unary_unary_rpc_method_handler(
            servicer.List,
            request_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.BaseProductListRequest.FromString,
            response_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.BaseProductListResponse.SerializeToString,
        ),
        "PartialUpdate": grpc.unary_unary_rpc_method_handler(
            servicer.PartialUpdate,
            request_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.BaseProductPartialUpdateRequest.FromString,
            response_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.BaseProductResponse.SerializeToString,
        ),
        "Retrieve": grpc.unary_unary_rpc_method_handler(
            servicer.Retrieve,
            request_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.BaseProductRetrieveRequest.FromString,
            response_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.BaseProductResponse.SerializeToString,
        ),
        "Update": grpc.unary_unary_rpc_method_handler(
            servicer.Update,
            request_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.BaseProductRequest.FromString,
            response_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.BaseProductResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "base_app.products_controller.BaseProductController", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class BaseProductController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/base_app.products_controller.BaseProductController/Create",
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.BaseProductRequest.SerializeToString,
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.BaseProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Destroy(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/base_app.products_controller.BaseProductController/Destroy",
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.BaseProductDestroyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def List(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/base_app.products_controller.BaseProductController/List",
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.BaseProductListRequest.SerializeToString,
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.BaseProductListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def PartialUpdate(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/base_app.products_controller.BaseProductController/PartialUpdate",
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.BaseProductPartialUpdateRequest.SerializeToString,
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.BaseProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Retrieve(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/base_app.products_controller.BaseProductController/Retrieve",
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.BaseProductRetrieveRequest.SerializeToString,
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.BaseProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Update(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/base_app.products_controller.BaseProductController/Update",
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.BaseProductRequest.SerializeToString,
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.BaseProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )


class CategoryControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
            "/base_app.products_controller.CategoryController/Create",
            request_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CategoryRequest.SerializeToString,
            response_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CategoryResponse.FromString,
        )
        self.Destroy = channel.unary_unary(
            "/base_app.products_controller.CategoryController/Destroy",
            request_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CategoryDestroyRequest.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
        self.List = channel.unary_unary(
            "/base_app.products_controller.CategoryController/List",
            request_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CategoryListRequest.SerializeToString,
            response_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CategoryListResponse.FromString,
        )
        self.PartialUpdate = channel.unary_unary(
            "/base_app.products_controller.CategoryController/PartialUpdate",
            request_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CategoryPartialUpdateRequest.SerializeToString,
            response_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CategoryResponse.FromString,
        )
        self.Retrieve = channel.unary_unary(
            "/base_app.products_controller.CategoryController/Retrieve",
            request_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CategoryRetrieveRequest.SerializeToString,
            response_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CategoryResponse.FromString,
        )
        self.Update = channel.unary_unary(
            "/base_app.products_controller.CategoryController/Update",
            request_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CategoryRequest.SerializeToString,
            response_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CategoryResponse.FromString,
        )


class CategoryControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def PartialUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_CategoryControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Create": grpc.unary_unary_rpc_method_handler(
            servicer.Create,
            request_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CategoryRequest.FromString,
            response_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CategoryResponse.SerializeToString,
        ),
        "Destroy": grpc.unary_unary_rpc_method_handler(
            servicer.Destroy,
            request_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CategoryDestroyRequest.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        "List": grpc.unary_unary_rpc_method_handler(
            servicer.List,
            request_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CategoryListRequest.FromString,
            response_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CategoryListResponse.SerializeToString,
        ),
        "PartialUpdate": grpc.unary_unary_rpc_method_handler(
            servicer.PartialUpdate,
            request_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CategoryPartialUpdateRequest.FromString,
            response_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CategoryResponse.SerializeToString,
        ),
        "Retrieve": grpc.unary_unary_rpc_method_handler(
            servicer.Retrieve,
            request_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CategoryRetrieveRequest.FromString,
            response_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CategoryResponse.SerializeToString,
        ),
        "Update": grpc.unary_unary_rpc_method_handler(
            servicer.Update,
            request_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CategoryRequest.FromString,
            response_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CategoryResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "base_app.products_controller.CategoryController", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class CategoryController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/base_app.products_controller.CategoryController/Create",
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CategoryRequest.SerializeToString,
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CategoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Destroy(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/base_app.products_controller.CategoryController/Destroy",
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CategoryDestroyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def List(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/base_app.products_controller.CategoryController/List",
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CategoryListRequest.SerializeToString,
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CategoryListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def PartialUpdate(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/base_app.products_controller.CategoryController/PartialUpdate",
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CategoryPartialUpdateRequest.SerializeToString,
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CategoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Retrieve(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/base_app.products_controller.CategoryController/Retrieve",
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CategoryRetrieveRequest.SerializeToString,
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CategoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Update(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/base_app.products_controller.CategoryController/Update",
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CategoryRequest.SerializeToString,
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CategoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )


class CoffeeMachineControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
            "/base_app.products_controller.CoffeeMachineController/Create",
            request_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CoffeeMachineRequest.SerializeToString,
            response_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CoffeeMachineResponse.FromString,
        )
        self.Destroy = channel.unary_unary(
            "/base_app.products_controller.CoffeeMachineController/Destroy",
            request_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CoffeeMachineDestroyRequest.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
        self.List = channel.unary_unary(
            "/base_app.products_controller.CoffeeMachineController/List",
            request_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CoffeeMachineListRequest.SerializeToString,
            response_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CoffeeMachineListResponse.FromString,
        )
        self.PartialUpdate = channel.unary_unary(
            "/base_app.products_controller.CoffeeMachineController/PartialUpdate",
            request_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CoffeeMachinePartialUpdateRequest.SerializeToString,
            response_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CoffeeMachineResponse.FromString,
        )
        self.Retrieve = channel.unary_unary(
            "/base_app.products_controller.CoffeeMachineController/Retrieve",
            request_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CoffeeMachineRetrieveRequest.SerializeToString,
            response_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CoffeeMachineResponse.FromString,
        )
        self.Update = channel.unary_unary(
            "/base_app.products_controller.CoffeeMachineController/Update",
            request_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CoffeeMachineRequest.SerializeToString,
            response_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CoffeeMachineResponse.FromString,
        )


class CoffeeMachineControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def PartialUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_CoffeeMachineControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Create": grpc.unary_unary_rpc_method_handler(
            servicer.Create,
            request_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CoffeeMachineRequest.FromString,
            response_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CoffeeMachineResponse.SerializeToString,
        ),
        "Destroy": grpc.unary_unary_rpc_method_handler(
            servicer.Destroy,
            request_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CoffeeMachineDestroyRequest.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        "List": grpc.unary_unary_rpc_method_handler(
            servicer.List,
            request_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CoffeeMachineListRequest.FromString,
            response_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CoffeeMachineListResponse.SerializeToString,
        ),
        "PartialUpdate": grpc.unary_unary_rpc_method_handler(
            servicer.PartialUpdate,
            request_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CoffeeMachinePartialUpdateRequest.FromString,
            response_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CoffeeMachineResponse.SerializeToString,
        ),
        "Retrieve": grpc.unary_unary_rpc_method_handler(
            servicer.Retrieve,
            request_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CoffeeMachineRetrieveRequest.FromString,
            response_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CoffeeMachineResponse.SerializeToString,
        ),
        "Update": grpc.unary_unary_rpc_method_handler(
            servicer.Update,
            request_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CoffeeMachineRequest.FromString,
            response_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CoffeeMachineResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "base_app.products_controller.CoffeeMachineController", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class CoffeeMachineController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/base_app.products_controller.CoffeeMachineController/Create",
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CoffeeMachineRequest.SerializeToString,
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CoffeeMachineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Destroy(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/base_app.products_controller.CoffeeMachineController/Destroy",
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CoffeeMachineDestroyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def List(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/base_app.products_controller.CoffeeMachineController/List",
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CoffeeMachineListRequest.SerializeToString,
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CoffeeMachineListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def PartialUpdate(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/base_app.products_controller.CoffeeMachineController/PartialUpdate",
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CoffeeMachinePartialUpdateRequest.SerializeToString,
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CoffeeMachineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Retrieve(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/base_app.products_controller.CoffeeMachineController/Retrieve",
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CoffeeMachineRetrieveRequest.SerializeToString,
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CoffeeMachineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Update(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/base_app.products_controller.CoffeeMachineController/Update",
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CoffeeMachineRequest.SerializeToString,
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.CoffeeMachineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )


class LedModeControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
            "/base_app.products_controller.LedModeController/Create",
            request_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedModeRequest.SerializeToString,
            response_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedModeResponse.FromString,
        )
        self.Destroy = channel.unary_unary(
            "/base_app.products_controller.LedModeController/Destroy",
            request_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedModeDestroyRequest.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
        self.List = channel.unary_unary(
            "/base_app.products_controller.LedModeController/List",
            request_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedModeListRequest.SerializeToString,
            response_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedModeListResponse.FromString,
        )
        self.PartialUpdate = channel.unary_unary(
            "/base_app.products_controller.LedModeController/PartialUpdate",
            request_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedModePartialUpdateRequest.SerializeToString,
            response_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedModeResponse.FromString,
        )
        self.Retrieve = channel.unary_unary(
            "/base_app.products_controller.LedModeController/Retrieve",
            request_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedModeRetrieveRequest.SerializeToString,
            response_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedModeResponse.FromString,
        )
        self.Update = channel.unary_unary(
            "/base_app.products_controller.LedModeController/Update",
            request_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedModeRequest.SerializeToString,
            response_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedModeResponse.FromString,
        )


class LedModeControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def PartialUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_LedModeControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Create": grpc.unary_unary_rpc_method_handler(
            servicer.Create,
            request_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedModeRequest.FromString,
            response_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedModeResponse.SerializeToString,
        ),
        "Destroy": grpc.unary_unary_rpc_method_handler(
            servicer.Destroy,
            request_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedModeDestroyRequest.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        "List": grpc.unary_unary_rpc_method_handler(
            servicer.List,
            request_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedModeListRequest.FromString,
            response_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedModeListResponse.SerializeToString,
        ),
        "PartialUpdate": grpc.unary_unary_rpc_method_handler(
            servicer.PartialUpdate,
            request_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedModePartialUpdateRequest.FromString,
            response_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedModeResponse.SerializeToString,
        ),
        "Retrieve": grpc.unary_unary_rpc_method_handler(
            servicer.Retrieve,
            request_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedModeRetrieveRequest.FromString,
            response_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedModeResponse.SerializeToString,
        ),
        "Update": grpc.unary_unary_rpc_method_handler(
            servicer.Update,
            request_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedModeRequest.FromString,
            response_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedModeResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "base_app.products_controller.LedModeController", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class LedModeController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/base_app.products_controller.LedModeController/Create",
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedModeRequest.SerializeToString,
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedModeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Destroy(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/base_app.products_controller.LedModeController/Destroy",
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedModeDestroyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def List(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/base_app.products_controller.LedModeController/List",
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedModeListRequest.SerializeToString,
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedModeListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def PartialUpdate(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/base_app.products_controller.LedModeController/PartialUpdate",
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedModePartialUpdateRequest.SerializeToString,
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedModeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Retrieve(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/base_app.products_controller.LedModeController/Retrieve",
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedModeRetrieveRequest.SerializeToString,
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedModeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Update(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/base_app.products_controller.LedModeController/Update",
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedModeRequest.SerializeToString,
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedModeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )


class LedPanelControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
            "/base_app.products_controller.LedPanelController/Create",
            request_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedPanelRequest.SerializeToString,
            response_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedPanelResponse.FromString,
        )
        self.Destroy = channel.unary_unary(
            "/base_app.products_controller.LedPanelController/Destroy",
            request_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedPanelDestroyRequest.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
        self.List = channel.unary_unary(
            "/base_app.products_controller.LedPanelController/List",
            request_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedPanelListRequest.SerializeToString,
            response_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedPanelListResponse.FromString,
        )
        self.PartialUpdate = channel.unary_unary(
            "/base_app.products_controller.LedPanelController/PartialUpdate",
            request_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedPanelPartialUpdateRequest.SerializeToString,
            response_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedPanelResponse.FromString,
        )
        self.Retrieve = channel.unary_unary(
            "/base_app.products_controller.LedPanelController/Retrieve",
            request_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedPanelRetrieveRequest.SerializeToString,
            response_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedPanelResponse.FromString,
        )
        self.Update = channel.unary_unary(
            "/base_app.products_controller.LedPanelController/Update",
            request_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedPanelRequest.SerializeToString,
            response_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedPanelResponse.FromString,
        )


class LedPanelControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def PartialUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_LedPanelControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Create": grpc.unary_unary_rpc_method_handler(
            servicer.Create,
            request_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedPanelRequest.FromString,
            response_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedPanelResponse.SerializeToString,
        ),
        "Destroy": grpc.unary_unary_rpc_method_handler(
            servicer.Destroy,
            request_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedPanelDestroyRequest.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        "List": grpc.unary_unary_rpc_method_handler(
            servicer.List,
            request_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedPanelListRequest.FromString,
            response_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedPanelListResponse.SerializeToString,
        ),
        "PartialUpdate": grpc.unary_unary_rpc_method_handler(
            servicer.PartialUpdate,
            request_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedPanelPartialUpdateRequest.FromString,
            response_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedPanelResponse.SerializeToString,
        ),
        "Retrieve": grpc.unary_unary_rpc_method_handler(
            servicer.Retrieve,
            request_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedPanelRetrieveRequest.FromString,
            response_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedPanelResponse.SerializeToString,
        ),
        "Update": grpc.unary_unary_rpc_method_handler(
            servicer.Update,
            request_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedPanelRequest.FromString,
            response_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedPanelResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "base_app.products_controller.LedPanelController", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class LedPanelController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/base_app.products_controller.LedPanelController/Create",
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedPanelRequest.SerializeToString,
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedPanelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Destroy(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/base_app.products_controller.LedPanelController/Destroy",
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedPanelDestroyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def List(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/base_app.products_controller.LedPanelController/List",
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedPanelListRequest.SerializeToString,
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedPanelListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def PartialUpdate(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/base_app.products_controller.LedPanelController/PartialUpdate",
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedPanelPartialUpdateRequest.SerializeToString,
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedPanelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Retrieve(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/base_app.products_controller.LedPanelController/Retrieve",
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedPanelRetrieveRequest.SerializeToString,
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedPanelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Update(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/base_app.products_controller.LedPanelController/Update",
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedPanelRequest.SerializeToString,
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.LedPanelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )


class ProjectControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
            "/base_app.products_controller.ProjectController/Create",
            request_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.ProjectRequest.SerializeToString,
            response_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.ProjectResponse.FromString,
        )
        self.Destroy = channel.unary_unary(
            "/base_app.products_controller.ProjectController/Destroy",
            request_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.ProjectDestroyRequest.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
        self.List = channel.unary_unary(
            "/base_app.products_controller.ProjectController/List",
            request_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.ProjectListRequest.SerializeToString,
            response_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.ProjectListResponse.FromString,
        )
        self.PartialUpdate = channel.unary_unary(
            "/base_app.products_controller.ProjectController/PartialUpdate",
            request_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.ProjectPartialUpdateRequest.SerializeToString,
            response_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.ProjectResponse.FromString,
        )
        self.Retrieve = channel.unary_unary(
            "/base_app.products_controller.ProjectController/Retrieve",
            request_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.ProjectRetrieveRequest.SerializeToString,
            response_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.ProjectResponse.FromString,
        )
        self.Update = channel.unary_unary(
            "/base_app.products_controller.ProjectController/Update",
            request_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.ProjectRequest.SerializeToString,
            response_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.ProjectResponse.FromString,
        )


class ProjectControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def PartialUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ProjectControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Create": grpc.unary_unary_rpc_method_handler(
            servicer.Create,
            request_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.ProjectRequest.FromString,
            response_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.ProjectResponse.SerializeToString,
        ),
        "Destroy": grpc.unary_unary_rpc_method_handler(
            servicer.Destroy,
            request_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.ProjectDestroyRequest.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        "List": grpc.unary_unary_rpc_method_handler(
            servicer.List,
            request_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.ProjectListRequest.FromString,
            response_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.ProjectListResponse.SerializeToString,
        ),
        "PartialUpdate": grpc.unary_unary_rpc_method_handler(
            servicer.PartialUpdate,
            request_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.ProjectPartialUpdateRequest.FromString,
            response_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.ProjectResponse.SerializeToString,
        ),
        "Retrieve": grpc.unary_unary_rpc_method_handler(
            servicer.Retrieve,
            request_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.ProjectRetrieveRequest.FromString,
            response_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.ProjectResponse.SerializeToString,
        ),
        "Update": grpc.unary_unary_rpc_method_handler(
            servicer.Update,
            request_deserializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.ProjectRequest.FromString,
            response_serializer=features_dot_products__controller_dot_grpc_dot_products__controller__pb2.ProjectResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "base_app.products_controller.ProjectController", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class ProjectController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/base_app.products_controller.ProjectController/Create",
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.ProjectRequest.SerializeToString,
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.ProjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Destroy(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/base_app.products_controller.ProjectController/Destroy",
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.ProjectDestroyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def List(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/base_app.products_controller.ProjectController/List",
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.ProjectListRequest.SerializeToString,
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.ProjectListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def PartialUpdate(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/base_app.products_controller.ProjectController/PartialUpdate",
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.ProjectPartialUpdateRequest.SerializeToString,
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.ProjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Retrieve(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/base_app.products_controller.ProjectController/Retrieve",
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.ProjectRetrieveRequest.SerializeToString,
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.ProjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Update(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/base_app.products_controller.ProjectController/Update",
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.ProjectRequest.SerializeToString,
            features_dot_products__controller_dot_grpc_dot_products__controller__pb2.ProjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
